import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const fcMinimal = localFont({
  src: [
    {
      path: "../public/fonts/FC Minimal Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-fc-minimal",
});

const ibmPlexSansThaiLooped = localFont({
  src: [
    {
      path: "../public/fonts/IBMPlexSansThaiLooped-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/IBMPlexSansThaiLooped-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-ibm-plex-sans-thai-looped",
});

export const metadata: Metadata = {
  title: "Referendum",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fcMinimal.variable} ${ibmPlexSansThaiLooped.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}